// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[document]/index.tsx";
import * as $1 from "./routes/[document]/raw/[page].tsx";
import * as $2 from "./routes/[document]/raw/index.tsx";
import * as $3 from "./routes/api/pdf.ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/DocumentPreviewHandler.tsx";

const manifest = {
  routes: {
    "./routes/[document]/index.tsx": $0,
    "./routes/[document]/raw/[page].tsx": $1,
    "./routes/[document]/raw/index.tsx": $2,
    "./routes/api/pdf.ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/DocumentPreviewHandler.tsx": $$0,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
